development:
  adapter: postgresql
  encoding: unicode
  database: geounivers_development
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: geounivers_production
  pool: 5
  username: postgres
  password: postgres
